name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: |
        brew install pkg-config
        brew install ncurses
    - name: make
      run: make
    - name: make
      run: make
    - name: make
      run: make
