name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: |
        export PKG_CONFIG_PATH="$(brew --prefix ncurses)/lib/pkgconfig"
        brew install pkg-config
        brew install ncurses
    - name: make engine
      run: make no-ncurses all
    - name: make tests
      run: make no-ncurses test2
    - name: make debug
      run: make no-ncurses debug
